{ Altium DelphiScript - Create Footprint: SO-8EP }
{ Generated by FootprintAI }
{
  Footprint: SO-8EP
  Description: SOIC-8 with exposed thermal pad - Ground Truth Test
  Pads: 9
  Vias: 6
}

Procedure CreateFootprint_SO_8EP;
Var
    Board      : IPCB_Board;
    CurrentLib : IPCB_Library;
    NewComp    : IPCB_LibComponent;
    Pad        : IPCB_Pad;
    Via        : IPCB_Via;
    Track      : IPCB_Track;
    Arc        : IPCB_Arc;
Begin
    // Try to get current PCB Library directly
    CurrentLib := PCBServer.GetCurrentPCBLibrary;

    // If that fails, try via the board interface
    If CurrentLib = Nil Then
    Begin
        Board := PCBServer.GetCurrentPCBBoard;
        If Board <> Nil Then
        Begin
            If Board.IsLibrary Then
                CurrentLib := PCBServer.GetCurrentPCBLibrary;
        End;
    End;

    If CurrentLib = Nil Then
    Begin
        ShowMessage('Please open a PCB Library document first.' + #13#10 +
                    'Make sure the library tab is active/focused.');
        Exit;
    End;

    // Create a new footprint component
    NewComp := PCBServer.CreatePCBLibComp;
    If NewComp = Nil Then
    Begin
        ShowMessage('Failed to create component.');
        Exit;
    End;

    NewComp.Name := 'SO-8EP';
    NewComp.Description := 'SOIC-8 with exposed thermal pad - Ground Truth Test';

    // Begin modification
    PCBServer.PreProcess;

    // --- Pad 1: 1 ---
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    If Pad <> Nil Then
    Begin
        Pad.X := MMsToCoord(-2.4980);
        Pad.Y := MMsToCoord(1.9050);
        Pad.Name := '1';
        Pad.Layer := eTopLayer;
        Pad.Mode := ePadMode_Simple;
        Pad.TopShape := eRectangular;
        Pad.TopXSize := MMsToCoord(0.8020);
        Pad.TopYSize := MMsToCoord(1.5050);
        Pad.Rotation := 90.000;
        NewComp.AddPCBObject(Pad);
    End;

    // --- Pad 2: 2 ---
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    If Pad <> Nil Then
    Begin
        Pad.X := MMsToCoord(-2.4980);
        Pad.Y := MMsToCoord(0.6350);
        Pad.Name := '2';
        Pad.Layer := eTopLayer;
        Pad.Mode := ePadMode_Simple;
        Pad.TopShape := eRectangular;
        Pad.TopXSize := MMsToCoord(0.8020);
        Pad.TopYSize := MMsToCoord(1.5050);
        Pad.Rotation := 90.000;
        NewComp.AddPCBObject(Pad);
    End;

    // --- Pad 3: 3 ---
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    If Pad <> Nil Then
    Begin
        Pad.X := MMsToCoord(-2.4980);
        Pad.Y := MMsToCoord(-0.6350);
        Pad.Name := '3';
        Pad.Layer := eTopLayer;
        Pad.Mode := ePadMode_Simple;
        Pad.TopShape := eRectangular;
        Pad.TopXSize := MMsToCoord(0.8020);
        Pad.TopYSize := MMsToCoord(1.5050);
        Pad.Rotation := 90.000;
        NewComp.AddPCBObject(Pad);
    End;

    // --- Pad 4: 4 ---
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    If Pad <> Nil Then
    Begin
        Pad.X := MMsToCoord(-2.4980);
        Pad.Y := MMsToCoord(-1.9050);
        Pad.Name := '4';
        Pad.Layer := eTopLayer;
        Pad.Mode := ePadMode_Simple;
        Pad.TopShape := eRectangular;
        Pad.TopXSize := MMsToCoord(0.8020);
        Pad.TopYSize := MMsToCoord(1.5050);
        Pad.Rotation := 90.000;
        NewComp.AddPCBObject(Pad);
    End;

    // --- Pad 5: 5 ---
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    If Pad <> Nil Then
    Begin
        Pad.X := MMsToCoord(2.4970);
        Pad.Y := MMsToCoord(-1.9050);
        Pad.Name := '5';
        Pad.Layer := eTopLayer;
        Pad.Mode := ePadMode_Simple;
        Pad.TopShape := eRectangular;
        Pad.TopXSize := MMsToCoord(0.8020);
        Pad.TopYSize := MMsToCoord(1.5050);
        Pad.Rotation := 90.000;
        NewComp.AddPCBObject(Pad);
    End;

    // --- Pad 6: 6 ---
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    If Pad <> Nil Then
    Begin
        Pad.X := MMsToCoord(2.4970);
        Pad.Y := MMsToCoord(-0.6350);
        Pad.Name := '6';
        Pad.Layer := eTopLayer;
        Pad.Mode := ePadMode_Simple;
        Pad.TopShape := eRectangular;
        Pad.TopXSize := MMsToCoord(0.8020);
        Pad.TopYSize := MMsToCoord(1.5050);
        Pad.Rotation := 90.000;
        NewComp.AddPCBObject(Pad);
    End;

    // --- Pad 7: 7 ---
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    If Pad <> Nil Then
    Begin
        Pad.X := MMsToCoord(2.4970);
        Pad.Y := MMsToCoord(0.6350);
        Pad.Name := '7';
        Pad.Layer := eTopLayer;
        Pad.Mode := ePadMode_Simple;
        Pad.TopShape := eRectangular;
        Pad.TopXSize := MMsToCoord(0.8020);
        Pad.TopYSize := MMsToCoord(1.5050);
        Pad.Rotation := 90.000;
        NewComp.AddPCBObject(Pad);
    End;

    // --- Pad 8: 8 ---
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    If Pad <> Nil Then
    Begin
        Pad.X := MMsToCoord(2.4970);
        Pad.Y := MMsToCoord(1.9050);
        Pad.Name := '8';
        Pad.Layer := eTopLayer;
        Pad.Mode := ePadMode_Simple;
        Pad.TopShape := eRectangular;
        Pad.TopXSize := MMsToCoord(0.8020);
        Pad.TopYSize := MMsToCoord(1.5050);
        Pad.Rotation := 90.000;
        NewComp.AddPCBObject(Pad);
    End;

    // --- Pad 9: 9 ---
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    If Pad <> Nil Then
    Begin
        Pad.X := MMsToCoord(0.0000);
        Pad.Y := MMsToCoord(0.0000);
        Pad.Name := '9';
        Pad.Layer := eTopLayer;
        Pad.Mode := ePadMode_Simple;
        Pad.TopShape := eRectangular;
        Pad.TopXSize := MMsToCoord(2.6130);
        Pad.TopYSize := MMsToCoord(3.5020);
        NewComp.AddPCBObject(Pad);
    End;

    // --- Via 1 ---
    Via := PCBServer.PCBObjectFactory(eViaObject, eNoDimension, eCreate_Default);
    If Via <> Nil Then
    Begin
        Via.X := MMsToCoord(-0.5500);
        Via.Y := MMsToCoord(-1.1000);
        Via.Size := MMsToCoord(0.5000);
        Via.HoleSize := MMsToCoord(0.2000);
        Via.LowLayer := eTopLayer;
        Via.HighLayer := eBottomLayer;
        NewComp.AddPCBObject(Via);
    End;

    // --- Via 2 ---
    Via := PCBServer.PCBObjectFactory(eViaObject, eNoDimension, eCreate_Default);
    If Via <> Nil Then
    Begin
        Via.X := MMsToCoord(-0.5500);
        Via.Y := MMsToCoord(0.0000);
        Via.Size := MMsToCoord(0.5000);
        Via.HoleSize := MMsToCoord(0.2000);
        Via.LowLayer := eTopLayer;
        Via.HighLayer := eBottomLayer;
        NewComp.AddPCBObject(Via);
    End;

    // --- Via 3 ---
    Via := PCBServer.PCBObjectFactory(eViaObject, eNoDimension, eCreate_Default);
    If Via <> Nil Then
    Begin
        Via.X := MMsToCoord(-0.5500);
        Via.Y := MMsToCoord(1.1000);
        Via.Size := MMsToCoord(0.5000);
        Via.HoleSize := MMsToCoord(0.2000);
        Via.LowLayer := eTopLayer;
        Via.HighLayer := eBottomLayer;
        NewComp.AddPCBObject(Via);
    End;

    // --- Via 4 ---
    Via := PCBServer.PCBObjectFactory(eViaObject, eNoDimension, eCreate_Default);
    If Via <> Nil Then
    Begin
        Via.X := MMsToCoord(0.5500);
        Via.Y := MMsToCoord(-1.1000);
        Via.Size := MMsToCoord(0.5000);
        Via.HoleSize := MMsToCoord(0.2000);
        Via.LowLayer := eTopLayer;
        Via.HighLayer := eBottomLayer;
        NewComp.AddPCBObject(Via);
    End;

    // --- Via 5 ---
    Via := PCBServer.PCBObjectFactory(eViaObject, eNoDimension, eCreate_Default);
    If Via <> Nil Then
    Begin
        Via.X := MMsToCoord(0.5500);
        Via.Y := MMsToCoord(0.0000);
        Via.Size := MMsToCoord(0.5000);
        Via.HoleSize := MMsToCoord(0.2000);
        Via.LowLayer := eTopLayer;
        Via.HighLayer := eBottomLayer;
        NewComp.AddPCBObject(Via);
    End;

    // --- Via 6 ---
    Via := PCBServer.PCBObjectFactory(eViaObject, eNoDimension, eCreate_Default);
    If Via <> Nil Then
    Begin
        Via.X := MMsToCoord(0.5500);
        Via.Y := MMsToCoord(1.1000);
        Via.Size := MMsToCoord(0.5000);
        Via.HoleSize := MMsToCoord(0.2000);
        Via.LowLayer := eTopLayer;
        Via.HighLayer := eBottomLayer;
        NewComp.AddPCBObject(Via);
    End;

    // --- Silkscreen Outline ---
    Track := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    If Track <> Nil Then
    Begin
        Track.X1 := MMsToCoord(-2.5000);
        Track.Y1 := MMsToCoord(-2.0000);
        Track.X2 := MMsToCoord(2.5000);
        Track.Y2 := MMsToCoord(-2.0000);
        Track.Width := MMsToCoord(0.1500);
        Track.Layer := eTopOverlay;
        NewComp.AddPCBObject(Track);
    End;

    Track := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    If Track <> Nil Then
    Begin
        Track.X1 := MMsToCoord(2.5000);
        Track.Y1 := MMsToCoord(-2.0000);
        Track.X2 := MMsToCoord(2.5000);
        Track.Y2 := MMsToCoord(2.0000);
        Track.Width := MMsToCoord(0.1500);
        Track.Layer := eTopOverlay;
        NewComp.AddPCBObject(Track);
    End;

    Track := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    If Track <> Nil Then
    Begin
        Track.X1 := MMsToCoord(2.5000);
        Track.Y1 := MMsToCoord(2.0000);
        Track.X2 := MMsToCoord(-2.5000);
        Track.Y2 := MMsToCoord(2.0000);
        Track.Width := MMsToCoord(0.1500);
        Track.Layer := eTopOverlay;
        NewComp.AddPCBObject(Track);
    End;

    Track := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    If Track <> Nil Then
    Begin
        Track.X1 := MMsToCoord(-2.5000);
        Track.Y1 := MMsToCoord(2.0000);
        Track.X2 := MMsToCoord(-2.5000);
        Track.Y2 := MMsToCoord(-2.0000);
        Track.Width := MMsToCoord(0.1500);
        Track.Layer := eTopOverlay;
        NewComp.AddPCBObject(Track);
    End;

    // --- Pin 1 Indicator ---
    Arc := PCBServer.PCBObjectFactory(eArcObject, eNoDimension, eCreate_Default);
    If Arc <> Nil Then
    Begin
        Arc.XCenter := MMsToCoord(-2.9980);
        Arc.YCenter := MMsToCoord(2.4050);
        Arc.Radius := MMsToCoord(0.25);
        Arc.StartAngle := 0;
        Arc.EndAngle := 360;
        Arc.LineWidth := MMsToCoord(0.15);
        Arc.Layer := eTopOverlay;
        NewComp.AddPCBObject(Arc);
    End;

    // End modification
    PCBServer.PostProcess;

    // Register the component in the library
    CurrentLib.RegisterComponent(NewComp);
    CurrentLib.CurrentComponent := NewComp;

    // Refresh the library view
    CurrentLib.Board.ViewManager_FullUpdate;
    CurrentLib.RefreshView;

    ShowMessage('Footprint SO-8EP created successfully!');
End;

{ Main entry point }
Procedure Run;
Begin
    CreateFootprint_SO_8EP;
End;
