{ Altium DelphiScript - Create Footprint: TEST-ALL-SHAPES }
{ Generated by FootprintAI }
{
  Footprint: TEST-ALL-SHAPES
  Description: Test all pad shapes: Round, Rectangular, Rounded Rectangle, Oval
  Pads: 4
  Vias: 0
}

Procedure CreateFootprint_TEST_ALL_SHAPES;
Var
    Board      : IPCB_Board;
    CurrentLib : IPCB_Library;
    NewComp    : IPCB_LibComponent;
    Pad        : IPCB_Pad;
    Via        : IPCB_Via;
    Track      : IPCB_Track;
    Arc        : IPCB_Arc;
Begin
    // Try to get current PCB Library directly
    CurrentLib := PCBServer.GetCurrentPCBLibrary;

    // If that fails, try via the board interface
    If CurrentLib = Nil Then
    Begin
        Board := PCBServer.GetCurrentPCBBoard;
        If Board <> Nil Then
        Begin
            If Board.IsLibrary Then
                CurrentLib := PCBServer.GetCurrentPCBLibrary;
        End;
    End;

    If CurrentLib = Nil Then
    Begin
        ShowMessage('Please open a PCB Library document first.' + #13#10 +
                    'Make sure the library tab is active/focused.');
        Exit;
    End;

    // Create a new footprint component
    NewComp := PCBServer.CreatePCBLibComp;
    If NewComp = Nil Then
    Begin
        ShowMessage('Failed to create component.');
        Exit;
    End;

    NewComp.Name := 'TEST-ALL-SHAPES';
    NewComp.Description := 'Test all pad shapes: Round, Rectangular, Rounded Rectangle, Oval';

    // Begin modification
    PCBServer.PreProcess;

    // --- Pad 1: 1 ---
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    If Pad <> Nil Then
    Begin
        Pad.X := MMsToCoord(-3.0000);
        Pad.Y := MMsToCoord(0.0000);
        Pad.Name := '1';
        Pad.Layer := eTopLayer;
        Pad.Mode := ePadMode_Simple;
        Pad.TopShape := eRounded;
        Pad.TopXSize := MMsToCoord(1.5000);
        Pad.TopYSize := MMsToCoord(1.5000);
        NewComp.AddPCBObject(Pad);
    End;

    // --- Pad 2: 2 ---
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    If Pad <> Nil Then
    Begin
        Pad.X := MMsToCoord(-1.0000);
        Pad.Y := MMsToCoord(0.0000);
        Pad.Name := '2';
        Pad.Layer := eTopLayer;
        Pad.Mode := ePadMode_Simple;
        Pad.TopShape := eRectangular;
        Pad.TopXSize := MMsToCoord(1.0000);
        Pad.TopYSize := MMsToCoord(1.5000);
        NewComp.AddPCBObject(Pad);
    End;

    // --- Pad 3: 3 ---
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    If Pad <> Nil Then
    Begin
        Pad.X := MMsToCoord(1.0000);
        Pad.Y := MMsToCoord(0.0000);
        Pad.Name := '3';
        Pad.Layer := eTopLayer;
        Pad.Mode := ePadMode_Simple;
        Pad.TopShape := eRectangular;
        Pad.TopXSize := MMsToCoord(1.0000);
        Pad.TopYSize := MMsToCoord(1.5000);
        NewComp.AddPCBObject(Pad);
    End;

    // --- Pad 4: 4 ---
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    If Pad <> Nil Then
    Begin
        Pad.X := MMsToCoord(3.0000);
        Pad.Y := MMsToCoord(0.0000);
        Pad.Name := '4';
        Pad.Layer := eTopLayer;
        Pad.Mode := ePadMode_Simple;
        Pad.TopShape := eRounded;
        Pad.TopXSize := MMsToCoord(0.8000);
        Pad.TopYSize := MMsToCoord(1.5000);
        NewComp.AddPCBObject(Pad);
    End;

    // --- Silkscreen Outline ---
    Track := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    If Track <> Nil Then
    Begin
        Track.X1 := MMsToCoord(-5.0000);
        Track.Y1 := MMsToCoord(-1.5000);
        Track.X2 := MMsToCoord(5.0000);
        Track.Y2 := MMsToCoord(-1.5000);
        Track.Width := MMsToCoord(0.1500);
        Track.Layer := eTopOverlay;
        NewComp.AddPCBObject(Track);
    End;

    Track := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    If Track <> Nil Then
    Begin
        Track.X1 := MMsToCoord(5.0000);
        Track.Y1 := MMsToCoord(-1.5000);
        Track.X2 := MMsToCoord(5.0000);
        Track.Y2 := MMsToCoord(1.5000);
        Track.Width := MMsToCoord(0.1500);
        Track.Layer := eTopOverlay;
        NewComp.AddPCBObject(Track);
    End;

    Track := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    If Track <> Nil Then
    Begin
        Track.X1 := MMsToCoord(5.0000);
        Track.Y1 := MMsToCoord(1.5000);
        Track.X2 := MMsToCoord(-5.0000);
        Track.Y2 := MMsToCoord(1.5000);
        Track.Width := MMsToCoord(0.1500);
        Track.Layer := eTopOverlay;
        NewComp.AddPCBObject(Track);
    End;

    Track := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    If Track <> Nil Then
    Begin
        Track.X1 := MMsToCoord(-5.0000);
        Track.Y1 := MMsToCoord(1.5000);
        Track.X2 := MMsToCoord(-5.0000);
        Track.Y2 := MMsToCoord(-1.5000);
        Track.Width := MMsToCoord(0.1500);
        Track.Layer := eTopOverlay;
        NewComp.AddPCBObject(Track);
    End;

    // --- Pin 1 Indicator ---
    Arc := PCBServer.PCBObjectFactory(eArcObject, eNoDimension, eCreate_Default);
    If Arc <> Nil Then
    Begin
        Arc.XCenter := MMsToCoord(-3.5000);
        Arc.YCenter := MMsToCoord(-0.5000);
        Arc.Radius := MMsToCoord(0.25);
        Arc.StartAngle := 0;
        Arc.EndAngle := 360;
        Arc.LineWidth := MMsToCoord(0.15);
        Arc.Layer := eTopOverlay;
        NewComp.AddPCBObject(Arc);
    End;

    // End modification
    PCBServer.PostProcess;

    // Register the component in the library
    CurrentLib.RegisterComponent(NewComp);
    CurrentLib.CurrentComponent := NewComp;

    // Refresh the library view
    CurrentLib.Board.ViewManager_FullUpdate;
    CurrentLib.RefreshView;

    ShowMessage('Footprint TEST-ALL-SHAPES created successfully!');
End;

{ Main entry point }
Procedure Run;
Begin
    CreateFootprint_TEST_ALL_SHAPES;
End;
