"""
Unit tests for Altium DelphiScript (.pas) generator.

Tests cover:
- Script structure and syntax
- Pad creation code generation
- Via creation code generation
- Outline track creation
- Pin 1 indicator
- Coordinate conversion calls
- All pad shapes and types

Run with: pytest backend/tests/test_generator_delphiscript.py -v
"""

import pytest
import tempfile
import os

from models import (
    Footprint,
    Pad,
    PadType,
    PadShape,
    Drill,
    DrillType,
    Via,
    Outline,
)
from generator_delphiscript import (
    DelphiScriptGenerator,
    generate_delphiscript,
    write_delphiscript,
)


# =============================================================================
# Fixtures
# =============================================================================


@pytest.fixture
def minimal_footprint():
    """Minimal footprint with one pad."""
    return Footprint(
        name="TEST-MINIMAL",
        pads=[Pad(designator="1", x=0, y=0, width=1.0, height=1.0)]
    )


@pytest.fixture
def smd_footprint():
    """SMD footprint with multiple pads."""
    pads = [
        Pad(designator="1", x=-2.498, y=1.905, width=0.802, height=1.505,
            rotation=90, shape=PadShape.RECTANGULAR, pad_type=PadType.SMD),
        Pad(designator="2", x=-2.498, y=0.635, width=0.802, height=1.505,
            rotation=90, shape=PadShape.RECTANGULAR, pad_type=PadType.SMD),
    ]
    return Footprint(name="SMD-TEST", pads=pads)


@pytest.fixture
def th_footprint():
    """Through-hole footprint."""
    pads = [
        Pad(designator="1", x=-2.54, y=0, width=1.5, height=1.5,
            shape=PadShape.ROUND, pad_type=PadType.THROUGH_HOLE,
            drill=Drill(diameter=0.9)),
        Pad(designator="2", x=2.54, y=0, width=1.5, height=1.5,
            shape=PadShape.ROUND, pad_type=PadType.THROUGH_HOLE,
            drill=Drill(diameter=0.9)),
    ]
    return Footprint(name="TH-TEST", pads=pads)


@pytest.fixture
def slotted_footprint():
    """Footprint with slotted holes."""
    pads = [
        Pad(designator="SH1", x=0, y=0, width=3.05, height=1.25,
            shape=PadShape.ROUND, pad_type=PadType.THROUGH_HOLE,
            drill=Drill(diameter=0.65, slot_length=2.45, drill_type=DrillType.SLOT)),
    ]
    return Footprint(name="SLOT-TEST", pads=pads)


@pytest.fixture
def footprint_with_vias():
    """Footprint with thermal vias."""
    vias = [
        Via(x=0.55, y=1.1, diameter=0.5, drill_diameter=0.2),
        Via(x=-0.55, y=1.1, diameter=0.5, drill_diameter=0.2),
    ]
    return Footprint(name="VIA-TEST", vias=vias)


@pytest.fixture
def footprint_with_outline():
    """Footprint with silkscreen outline."""
    pads = [Pad(designator="1", x=0, y=0, width=1.0, height=1.0)]
    return Footprint(
        name="OUTLINE-TEST",
        pads=pads,
        outline=Outline(width=5.0, height=4.0)
    )


# =============================================================================
# Script Structure Tests
# =============================================================================


class TestScriptStructure:
    """Tests for overall script structure."""

    def test_header_comment(self, minimal_footprint):
        """Test that script has header comment with footprint name."""
        script = generate_delphiscript(minimal_footprint)

        assert "{ Altium DelphiScript" in script
        assert "TEST-MINIMAL" in script
        assert "Generated by FootprintAI" in script

    def test_procedure_declaration(self, minimal_footprint):
        """Test that main procedure is declared."""
        script = generate_delphiscript(minimal_footprint)

        assert "Procedure CreateFootprint_TEST_MINIMAL;" in script
        assert "Var" in script
        assert "Begin" in script
        assert "End;" in script

    def test_run_procedure(self, minimal_footprint):
        """Test that Run entry point exists."""
        script = generate_delphiscript(minimal_footprint)

        assert "Procedure Run;" in script
        assert "CreateFootprint_TEST_MINIMAL;" in script

    def test_library_check(self, minimal_footprint):
        """Test that script checks for valid PCB library."""
        script = generate_delphiscript(minimal_footprint)

        assert "PCBServer.GetCurrentPCBLibrary" in script
        assert "If CurrentLib = Nil Then" in script
        # Also checks via Board.IsLibrary fallback
        assert "Board.IsLibrary" in script
        assert "ShowMessage" in script

    def test_pre_post_process(self, minimal_footprint):
        """Test that PreProcess/PostProcess are called."""
        script = generate_delphiscript(minimal_footprint)

        assert "PCBServer.PreProcess" in script
        assert "PCBServer.PostProcess" in script

    def test_view_refresh(self, minimal_footprint):
        """Test that view is refreshed at end."""
        script = generate_delphiscript(minimal_footprint)

        assert "CurrentLib.Board.ViewManager_FullUpdate" in script
        assert "CurrentLib.RefreshView" in script


# =============================================================================
# Pad Creation Tests
# =============================================================================


class TestPadCreation:
    """Tests for pad creation code."""

    def test_pad_factory_call(self, minimal_footprint):
        """Test that PCBObjectFactory is called for pads."""
        script = generate_delphiscript(minimal_footprint)

        assert "PCBServer.PCBObjectFactory(ePadObject" in script

    def test_pad_coordinates(self, smd_footprint):
        """Test that pad coordinates use MMsToCoord."""
        script = generate_delphiscript(smd_footprint)

        assert "Pad.X := MMsToCoord(-2.4980)" in script
        assert "Pad.Y := MMsToCoord(1.9050)" in script

    def test_pad_designator(self, smd_footprint):
        """Test that pad designators are set."""
        script = generate_delphiscript(smd_footprint)

        assert "Pad.Name := '1'" in script
        assert "Pad.Name := '2'" in script

    def test_smd_layer(self, smd_footprint):
        """Test that SMD pads use eTopLayer."""
        script = generate_delphiscript(smd_footprint)

        assert "Pad.Layer := eTopLayer" in script

    def test_th_layer(self, th_footprint):
        """Test that TH pads use eMultiLayer."""
        script = generate_delphiscript(th_footprint)

        assert "Pad.Layer := eMultiLayer" in script

    def test_pad_size(self, smd_footprint):
        """Test that pad sizes are set."""
        script = generate_delphiscript(smd_footprint)

        assert "Pad.TopXSize := MMsToCoord(0.8020)" in script
        assert "Pad.TopYSize := MMsToCoord(1.5050)" in script

    def test_pad_rotation(self, smd_footprint):
        """Test that pad rotation is set."""
        script = generate_delphiscript(smd_footprint)

        assert "Pad.Rotation := 90.000" in script

    def test_pad_shape_rectangular(self, smd_footprint):
        """Test rectangular pad shape."""
        script = generate_delphiscript(smd_footprint)

        assert "Pad.TopShape := eRectangular" in script

    def test_pad_shape_round(self, th_footprint):
        """Test round pad shape."""
        script = generate_delphiscript(th_footprint)

        assert "Pad.TopShape := eRounded" in script

    def test_pad_mode_simple(self, minimal_footprint):
        """Test that pad mode is set to simple."""
        script = generate_delphiscript(minimal_footprint)

        assert "Pad.Mode := ePadMode_Simple" in script

    def test_add_to_component(self, minimal_footprint):
        """Test that pads are added to the library component."""
        script = generate_delphiscript(minimal_footprint)

        assert "NewComp.AddPCBObject(Pad)" in script


# =============================================================================
# Drill Hole Tests
# =============================================================================


class TestDrillHoles:
    """Tests for drill hole creation."""

    def test_round_hole_size(self, th_footprint):
        """Test round drill hole size."""
        script = generate_delphiscript(th_footprint)

        assert "Pad.HoleSize := MMsToCoord(0.9000)" in script
        assert "Pad.HoleType := eRoundHole" in script

    def test_slot_hole_type(self, slotted_footprint):
        """Test slotted hole type."""
        script = generate_delphiscript(slotted_footprint)

        assert "Pad.HoleType := eSlotHole" in script

    def test_slot_dimensions_comment(self, slotted_footprint):
        """Test slot dimensions are commented."""
        script = generate_delphiscript(slotted_footprint)

        assert "Slot: 0.65mm width x 2.45mm length" in script


# =============================================================================
# Via Creation Tests
# =============================================================================


class TestViaCreation:
    """Tests for via creation code."""

    def test_via_factory_call(self, footprint_with_vias):
        """Test that PCBObjectFactory is called for vias."""
        script = generate_delphiscript(footprint_with_vias)

        assert "PCBServer.PCBObjectFactory(eViaObject" in script

    def test_via_coordinates(self, footprint_with_vias):
        """Test via coordinates."""
        script = generate_delphiscript(footprint_with_vias)

        assert "Via.X := MMsToCoord(0.5500)" in script
        assert "Via.Y := MMsToCoord(1.1000)" in script

    def test_via_size(self, footprint_with_vias):
        """Test via pad size."""
        script = generate_delphiscript(footprint_with_vias)

        assert "Via.Size := MMsToCoord(0.5000)" in script

    def test_via_hole_size(self, footprint_with_vias):
        """Test via drill size."""
        script = generate_delphiscript(footprint_with_vias)

        assert "Via.HoleSize := MMsToCoord(0.2000)" in script

    def test_via_layers(self, footprint_with_vias):
        """Test via layer assignment."""
        script = generate_delphiscript(footprint_with_vias)

        assert "Via.LowLayer := eTopLayer" in script
        assert "Via.HighLayer := eBottomLayer" in script


# =============================================================================
# Outline Creation Tests
# =============================================================================


class TestOutlineCreation:
    """Tests for silkscreen outline creation."""

    def test_track_factory_call(self, footprint_with_outline):
        """Test that tracks are created for outline."""
        script = generate_delphiscript(footprint_with_outline)

        assert "PCBServer.PCBObjectFactory(eTrackObject" in script

    def test_track_coordinates(self, footprint_with_outline):
        """Test track coordinates - calculated from pad bounds + clearance."""
        script = generate_delphiscript(footprint_with_outline)

        # Outline is now calculated from pads (1x1 pad at 0,0) + 0.3mm clearance
        # Expected bounds: -0.8 to 0.8 in both directions
        assert "Track.X1 := MMsToCoord(-0.8000)" in script
        assert "Track.Y1 := MMsToCoord(-0.8000)" in script

    def test_track_layer(self, footprint_with_outline):
        """Test track layer is TopOverlay."""
        script = generate_delphiscript(footprint_with_outline)

        assert "Track.Layer := eTopOverlay" in script

    def test_track_width(self, footprint_with_outline):
        """Test track line width."""
        script = generate_delphiscript(footprint_with_outline)

        assert "Track.Width := MMsToCoord(0.1500)" in script


# =============================================================================
# Pin 1 Indicator Tests
# =============================================================================


class TestPin1Indicator:
    """Tests for Pin 1 indicator creation."""

    def test_arc_factory_call(self, footprint_with_outline):
        """Test that arc is created for Pin 1 indicator."""
        script = generate_delphiscript(footprint_with_outline)

        assert "PCBServer.PCBObjectFactory(eArcObject" in script

    def test_arc_is_circle(self, footprint_with_outline):
        """Test arc forms complete circle."""
        script = generate_delphiscript(footprint_with_outline)

        assert "Arc.StartAngle := 0" in script
        assert "Arc.EndAngle := 360" in script

    def test_arc_layer(self, footprint_with_outline):
        """Test arc is on TopOverlay."""
        script = generate_delphiscript(footprint_with_outline)

        assert "Arc.Layer := eTopOverlay" in script


# =============================================================================
# All Pad Shapes Tests
# =============================================================================


class TestAllPadShapes:
    """Tests for all supported pad shapes."""

    def test_round_shape(self):
        """Test round pad shape constant."""
        footprint = Footprint(
            name="ROUND",
            pads=[Pad(designator="1", x=0, y=0, width=1, height=1,
                      shape=PadShape.ROUND)]
        )
        script = generate_delphiscript(footprint)
        assert "Pad.TopShape := eRounded" in script

    def test_rectangular_shape(self):
        """Test rectangular pad shape constant."""
        footprint = Footprint(
            name="RECT",
            pads=[Pad(designator="1", x=0, y=0, width=1, height=1,
                      shape=PadShape.RECTANGULAR)]
        )
        script = generate_delphiscript(footprint)
        assert "Pad.TopShape := eRectangular" in script

    def test_rounded_rectangle_shape(self):
        """Test rounded rectangle pad shape - uses eRectangular as AD26 fallback."""
        footprint = Footprint(
            name="ROUNDRECT",
            pads=[Pad(designator="1", x=0, y=0, width=1, height=1,
                      shape=PadShape.ROUNDED_RECTANGLE)]
        )
        script = generate_delphiscript(footprint)
        # MVP limitation: eRoundRectShape crashes AD26, using eRectangular
        assert "Pad.TopShape := eRectangular" in script

    def test_oval_shape(self):
        """Test oval pad shape (uses eRounded with different X/Y)."""
        footprint = Footprint(
            name="OVAL",
            pads=[Pad(designator="1", x=0, y=0, width=0.5, height=1.5,
                      shape=PadShape.OVAL)]
        )
        script = generate_delphiscript(footprint)
        assert "Pad.TopShape := eRounded" in script
        assert "Pad.TopXSize := MMsToCoord(0.5000)" in script
        assert "Pad.TopYSize := MMsToCoord(1.5000)" in script


# =============================================================================
# Convenience Function Tests
# =============================================================================


class TestConvenienceFunctions:
    """Tests for convenience functions."""

    def test_generate_delphiscript_function(self, smd_footprint):
        """Test generate_delphiscript function."""
        script = generate_delphiscript(smd_footprint)

        assert isinstance(script, str)
        assert "Procedure" in script
        assert "SMD_TEST" in script  # Safe name conversion

    def test_write_delphiscript_function(self, smd_footprint):
        """Test write_delphiscript function."""
        with tempfile.NamedTemporaryFile(suffix=".pas", delete=False) as f:
            filepath = f.name

        try:
            write_delphiscript(smd_footprint, filepath)

            assert os.path.exists(filepath)

            with open(filepath, "r") as f:
                content = f.read()

            assert "Procedure" in content
            assert "PCBServer" in content
        finally:
            if os.path.exists(filepath):
                os.remove(filepath)


# =============================================================================
# Name Sanitization Tests
# =============================================================================


class TestNameSanitization:
    """Tests for procedure name sanitization."""

    def test_special_characters_replaced(self):
        """Test that special chars become underscores."""
        footprint = Footprint(
            name="SO-8EP",
            pads=[Pad(designator="1", x=0, y=0, width=1, height=1)]
        )
        script = generate_delphiscript(footprint)

        assert "Procedure CreateFootprint_SO_8EP" in script

    def test_numeric_prefix_handled(self):
        """Test that numeric-starting names get prefix."""
        footprint = Footprint(
            name="0402",
            pads=[Pad(designator="1", x=0, y=0, width=1, height=1)]
        )
        script = generate_delphiscript(footprint)

        assert "Procedure CreateFootprint_FP_0402" in script
